# Generated by Django 4.2.1 on 2023-06-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_Name', models.CharField(max_length=20, null=True)),
                ('trainer_Email', models.EmailField(max_length=20, null=True)),
                ('trainer_Password', models.CharField(max_length=20, null=True)),
                ('trainer_Contact', models.IntegerField(max_length=20, null=True)),
                ('trainer_Address', models.CharField(max_length=30, null=True)),
                ('trainer_Gender', models.CharField(max_length=10, null=True)),
                ('trainer_DOB', models.DateField(max_length=10, null=True)),
            ],
        ),
    ]
