# Generated by Django 4.2.1 on 2023-06-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0004_doctor_tbl_doctor_id_number_doctor_tbl_doctor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_tbl',
            name='doctor_Contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor_tbl',
            name='doctor_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor_tbl',
            name='doctor_qualification',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='trainer_tbl',
            name='trainer_Contact',
            field=models.IntegerField(null=True),
        ),
    ]
