# Generated by Django 4.2.1 on 2023-06-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0005_alter_doctor_tbl_doctor_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_tbl',
            name='doctor_salary',
            field=models.IntegerField(null=True),
        ),
    ]
