# Generated by Django 4.2.1 on 2023-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0006_doctor_tbl_doctor_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='package_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20, null=True)),
                ('package_duration', models.IntegerField(null=True)),
                ('package_type', models.CharField(max_length=20, null=True)),
                ('package_price', models.IntegerField(null=True)),
                ('package_status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
