# Generated by Django 4.2.1 on 2023-06-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0009_event_tbl_products_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_tbl',
            old_name='event_wieghtlimit',
            new_name='event_weightlimit',
        ),
    ]
