# Generated by Django 4.2.1 on 2023-06-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0010_rename_event_wieghtlimit_event_tbl_event_weightlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='memberregistration_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('DOB', models.DateField(max_length=10, null=True)),
                ('Contact', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('place', models.CharField(max_length=20, null=True)),
                ('Pincode', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('DateOfJoining', models.DateField(null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('package_type', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
