# Generated by Django 4.2.1 on 2023-06-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0011_memberregistration_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberregistration_tbl',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.package_tbl'),
        ),
    ]
