# Generated by Django 4.2.1 on 2023-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0014_regpayment_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberregistration_tbl',
            old_name='Pincode',
            new_name='Age',
        ),
        migrations.AddField(
            model_name='memberregistration_tbl',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
