# Generated by Django 4.1.5 on 2023-07-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0026_member_health_details_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_health_details_tbl',
            old_name='memebrid',
            new_name='memberid',
        ),
    ]
