# Generated by Django 4.1.5 on 2023-07-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0028_doctor_member_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_member_report',
            name='signature',
            field=models.BinaryField(null=True),
        ),
    ]
