# Generated by Django 4.1.5 on 2023-07-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0033_workout_details_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout_details',
            name='performance',
        ),
        migrations.AddField(
            model_name='trainer_member_report',
            name='performance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
