# Generated by Django 4.1.5 on 2023-07-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0034_remove_workout_details_performance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=100, null=True)),
                ('memberemail', models.EmailField(max_length=254, null=True)),
                ('overall_exp', models.CharField(max_length=100, null=True)),
                ('behavior', models.CharField(max_length=100, null=True)),
                ('helpfulness', models.CharField(max_length=100, null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('Trainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.trainer_tbl')),
                ('memberid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl')),
            ],
        ),
    ]
