# Generated by Django 4.1.5 on 2023-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0036_trainer_feedback_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberbooking_tbl',
            name='pay',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
