# Generated by Django 4.2.1 on 2023-07-17 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0037_alter_memberbooking_tbl_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberbooking_tbl',
            name='memberid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl'),
        ),
    ]
