# Generated by Django 4.2.1 on 2023-07-19 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0040_remove_leave_dates_tbl_trainer_id_workoutlist_tbl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_leave_dates_tbl',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.doctor_tbl'),
        ),
        migrations.AddField(
            model_name='leave_dates_tbl',
            name='trainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.trainer_tbl'),
        ),
    ]
