# Generated by Django 4.2.1 on 2023-07-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0042_trainer_tbl_trainer_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_tbl',
            name='trainer_image',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
