# Generated by Django 4.2.1 on 2023-07-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0044_rename_trainer_image_trainer_tbl_trainer_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer_tbl',
            old_name='trainer_images',
            new_name='trainer_Images',
        ),
    ]
