# Generated by Django 4.2.1 on 2023-07-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0046_rename_trainer_images_trainer_tbl_trainer_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration_tbl',
            name='person_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
