# Generated by Django 4.2.1 on 2023-07-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0049_alter_doctorsalary_tbl_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('Product_image', models.ImageField(null=True, upload_to='media')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberbooking_tbl')),
            ],
        ),
    ]
