# Generated by Django 4.2.1 on 2023-07-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0051_take_appointment_tbl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntrainer_tbl',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
