# Generated by Django 4.2.1 on 2023-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0052_assigntrainer_tbl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntrainer_tbl',
            name='trainer_Contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assigntrainer_tbl',
            name='trainer_Email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assigntrainer_tbl',
            name='trainer_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
