# Generated by Django 4.2.1 on 2023-07-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0054_remove_assigntrainer_tbl_trainer_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_tbl',
            old_name='Name',
            new_name='full',
        ),
        migrations.RenameField(
            model_name='feedback_tbl',
            old_name='customer',
            new_name='memberid',
        ),
    ]
