# Generated by Django 4.2.1 on 2023-07-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0056_rename_full_feedback_tbl_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_tbl',
            old_name='member',
            new_name='memberid',
        ),
    ]
