# Generated by Django 4.1.5 on 2023-07-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0059_workoutlist_tbl_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_name',
            name='memberid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl'),
        ),
    ]
