# Generated by Django 4.2.1 on 2023-07-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0062_adddietplan_tbl_trainer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddietplan_tbl',
            name='membername',
        ),
    ]
