# Generated by Django 4.2.1 on 2023-07-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0063_remove_adddietplan_tbl_membername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlist_tbl',
            name='membername',
        ),
    ]
