# Generated by Django 4.2.1 on 2023-08-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0065_memberregistration_tbl_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_tbl',
            name='advanceamount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package_tbl',
            name='balanceamount',
            field=models.IntegerField(null=True),
        ),
    ]
