# Generated by Django 4.2.1 on 2023-08-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0066_package_tbl_advanceamount_package_tbl_balanceamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package_tbl',
            name='advanceamount',
        ),
        migrations.RemoveField(
            model_name='package_tbl',
            name='balanceamount',
        ),
        migrations.AddField(
            model_name='regpayment_tbl',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.package_tbl'),
        ),
    ]
