# Generated by Django 4.2.1 on 2023-08-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0068_remove_regpayment_tbl_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='regpayment_tbl',
            name='paid_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='MonthlyFeePayment_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('package_type', models.CharField(max_length=20, null=True)),
                ('totalamount', models.IntegerField(null=True)),
                ('totalpaid', models.IntegerField(null=True)),
                ('balanceamount', models.IntegerField(null=True)),
                ('monthlyPayment', models.IntegerField(null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('paymenttime', models.TimeField(auto_now_add=True, null=True)),
                ('paymentdate', models.DateField(auto_now_add=True, null=True)),
                ('memberid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl')),
                ('reg_payment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.regpayment_tbl')),
            ],
        ),
    ]
