# Generated by Django 4.2.1 on 2023-08-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0070_rename_reg_payment_id_monthlyfeepayment_tbl_reg_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfeepayment_tbl',
            name='pay',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
