# Generated by Django 4.2.1 on 2023-08-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0071_monthlyfeepayment_tbl_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='regpayment_tbl',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
