# Generated by Django 4.1.5 on 2023-08-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0072_regpayment_tbl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistration_tbl',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
