# Generated by Django 4.2.1 on 2023-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0008_remove_package_tbl_package_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20, null=True)),
                ('event_category', models.CharField(max_length=20, null=True)),
                ('event_agelimit', models.IntegerField(null=True)),
                ('event_wieghtlimit', models.IntegerField(null=True)),
                ('event_place', models.CharField(max_length=20, null=True)),
                ('event_date', models.DateField(null=True)),
                ('event_time', models.TimeField(null=True)),
                ('event_status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=20, null=True)),
                ('product_name', models.CharField(max_length=20, null=True)),
                ('product_details', models.CharField(max_length=50, null=True)),
                ('product_delivery_charge', models.IntegerField(null=True)),
                ('product_discounts', models.IntegerField(null=True)),
                ('product_totalprice', models.IntegerField(null=True)),
                ('product_status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
