# Generated by Django 4.2.1 on 2023-06-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0013_products_tbl_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegPayment_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=20, null=True)),
                ('totalamount', models.IntegerField(null=True)),
                ('advanceamount', models.IntegerField(null=True)),
                ('monthlyPayment', models.IntegerField(null=True)),
                ('balanceamount', models.IntegerField(null=True)),
                ('paymenttime', models.TimeField(auto_now_add=True, null=True)),
                ('paymentdate', models.DateField(auto_now_add=True, null=True)),
                ('memberid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl')),
            ],
        ),
    ]
