# Generated by Django 4.2.1 on 2023-06-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0018_scheduletime_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletime_tbl',
            name='membername',
        ),
    ]
