# Generated by Django 4.2.1 on 2023-06-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0021_remove_scheduletime_tbl_startime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_tbl',
            name='product_gst',
            field=models.IntegerField(null=True),
        ),
    ]
