# Generated by Django 4.2.1 on 2023-06-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0022_products_tbl_product_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products_tbl',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.product_category_tbl'),
        ),
    ]
