# Generated by Django 4.2.1 on 2023-07-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0023_product_category_tbl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.products_tbl')),
                ('memberid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl')),
            ],
        ),
    ]
