# Generated by Django 4.1.5 on 2023-07-13 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0025_memberbooking_tbl_feedback_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='member_health_details_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('bp', models.CharField(max_length=100, null=True)),
                ('heart_disease', models.CharField(max_length=100, null=True)),
                ('joint_problem', models.CharField(max_length=100, null=True)),
                ('dizziness', models.CharField(max_length=100, null=True)),
                ('memebrid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl')),
            ],
        ),
    ]
