# Generated by Django 4.1.5 on 2023-07-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0027_rename_memebrid_member_health_details_tbl_memberid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Member_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('previous_weight', models.IntegerField(null=True)),
                ('current_weight', models.IntegerField(null=True)),
                ('previous_height', models.IntegerField(null=True)),
                ('current_height', models.IntegerField(null=True)),
                ('medical_exam', models.CharField(max_length=100, null=True)),
                ('medical_test', models.CharField(max_length=100, null=True)),
                ('overall_condition', models.CharField(max_length=100, null=True)),
                ('instructions', models.CharField(max_length=100, null=True)),
                ('health_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.member_health_details_tbl')),
            ],
        ),
    ]
