# Generated by Django 4.1.5 on 2023-07-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0029_doctor_member_report_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_member_report',
            name='signature',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
