# Generated by Django 4.1.5 on 2023-07-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0030_alter_doctor_member_report_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='workout_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Workout', models.IntegerField(null=True)),
                ('Completed_Work_out', models.IntegerField(null=True)),
                ('Pending_Workout', models.IntegerField(null=True)),
                ('Total_Time_Taken', models.TimeField(null=True)),
                ('Date', models.DateField(null=True)),
                ('Trainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.trainer_tbl')),
                ('memberid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Member_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100, null=True)),
                ('Total_Workout', models.IntegerField(null=True)),
                ('Completed_Work_out', models.IntegerField(null=True)),
                ('Pending_Workout', models.IntegerField(null=True)),
                ('Total_Time_Taken', models.TimeField(null=True)),
                ('Trainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.trainer_tbl')),
                ('memberid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl')),
            ],
        ),
    ]
