# Generated by Django 4.1.5 on 2023-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0032_alter_trainer_member_report_total_time_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_details',
            name='performance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
