# Generated by Django 4.1.5 on 2023-07-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0035_trainer_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_Feedback_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_overall_exp', models.CharField(max_length=100, null=True)),
                ('total_behavior', models.CharField(max_length=100, null=True)),
                ('total_helpfulness', models.CharField(max_length=100, null=True)),
                ('instructions', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('Trainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.trainer_tbl')),
            ],
        ),
    ]
