# Generated by Django 4.2.1 on 2023-07-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0043_trainer_tbl_trainer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer_tbl',
            old_name='trainer_image',
            new_name='trainer_images',
        ),
    ]
