# Generated by Django 4.2.1 on 2023-07-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0047_memberregistration_tbl_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_tbl',
            name='doctor_images',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='Take_Appointment_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.doctor_tbl')),
                ('memberid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='AddDietPlan_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=100, null=True)),
                ('week', models.CharField(max_length=100, null=True)),
                ('day', models.CharField(max_length=100, null=True)),
                ('brkfst', models.CharField(max_length=100, null=True)),
                ('lunch', models.CharField(max_length=100, null=True)),
                ('snack', models.CharField(max_length=100, null=True)),
                ('dinner', models.CharField(max_length=100, null=True)),
                ('memberid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.memberregistration_tbl')),
            ],
        ),
    ]
