# Generated by Django 4.2.1 on 2023-07-21 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0048_doctor_tbl_doctor_images_take_appointment_tbl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsalary_tbl',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.doctor_tbl'),
        ),
    ]
