# Generated by Django 4.2.1 on 2023-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0050_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_appointment_tbl',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
