# Generated by Django 4.1.5 on 2023-07-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0060_exercise_name_memberid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_name',
            name='week',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
