# Generated by Django 4.1.5 on 2023-07-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0061_exercise_name_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddietplan_tbl',
            name='trainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitapp.trainer_tbl'),
        ),
    ]
